services:
  - type: web
    name: spjin
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ./render-build.sh
    startCommand: ./.build/release/App serve --env production --hostname 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spjin-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SWIFT_VERSION
        value: "5.9"

databases:
  - name: spjin-db
    databaseName: spjin
    user: spjin
